### ISSUE TITLE
missing 1 required positional argument: 'tokenizer'

### ISSUE THREAD

**Issue by wangxinyu0922** [sdadas/polish-roberta#7]
I get the following error when running `tokenizer = PreTrainedTokenizerFast(tokenizer_file="roberta_large_transformers/tokenizer.json")`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'tokenizer
```

Do you have any idea to solve it? By the way, I prefer to load the tokenizer by something like:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("roberta_large_transformers")
```
I tried such code but I failed to load that and getting the error:
```
  File "/home/yongjiang.jy/wangxy/flair/flair/embeddings.py", line 2927, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model, **kwargs)
  File "/home/yongjiang.jy/anaconda2/envs/parser/lib/python3.6/site-packages/transformers/tokenization_auto.py", line 217, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/yongjiang.jy/anaconda2/envs/parser/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1140, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/yongjiang.jy/anaconda2/envs/parser/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/yongjiang.jy/anaconda2/envs/parser/lib/python3.6/site-packages/transformers/tokenization_roberta.py", line 162, in __init__
    **kwargs,
  File "/home/yongjiang.jy/anaconda2/envs/parser/lib/python3.6/site-packages/transformers/tokenization_gpt2.py", line 157, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
It seems that the `vocab.json` is missing, do you have any idea about this?

Thank you!

**Comment by sdadas** [comment]
Which version of Huggingface Transformers are you using? I've checked with the newest version (4.6.0) and the example still works. 

For fast tokenizers, `vocab.json` file is not needed since vocab is already included in the `tokenizer.json` file.

**Comment by wangxinyu0922** [comment]
I use transformers 3.0.0. Maybe I should try a higher version. Thank you
